version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: user_auth
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 1d
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_auth
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-mysql-init:/docker-entrypoint-initdb.d

volumes:
  dbdata:
